# Generated by Django 2.1.7 on 2019-03-10 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_auto_20190310_1746'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropaciente',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='configuraciones.Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registropaciente',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='configuraciones.Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registropaciente',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='configuraciones.Municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registropaciente',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='configuraciones.Pais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registropaciente',
            name='parroquia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='configuraciones.Parroquia'),
            preserve_default=False,
        ),
    ]
