# Generated by Django 2.1.7 on 2019-03-07 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatologiasGenerales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_patologico', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Patologia',
                'ordering': ['nombre_patologico'],
                'db_table': 'configuracion"."listado_general_patologico',
                'verbose_name_plural': 'Patologias o Enfermedades',
            },
        ),
        migrations.CreateModel(
            name='PreguntaSecreta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pregunta Secreta',
                'ordering': ['nombre'],
                'db_table': 'configuracion"."pregunta_secreta',
                'verbose_name_plural': 'Preguntas Secretas',
            },
        ),
        migrations.CreateModel(
            name='SistemaAparatoBiologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_aparato', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Sistema o Aparato Biologico',
                'ordering': ['nombre_aparato'],
                'db_table': 'configuracion"."sistema_aparato_biologico',
                'verbose_name_plural': 'Sistema o Aparato Biologico',
            },
        ),
        migrations.AddField(
            model_name='patologiasgenerales',
            name='aparato_biologico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuraciones.SistemaAparatoBiologico'),
        ),
    ]
