# Generated by Django 2.1.7 on 2019-03-05 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatologiasGenerales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_patologico', models.CharField(max_length=150)),
                ('aparato_biologico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuraciones.SistemaAparatoBiologico')),
            ],
            options={
                'verbose_name': 'Patologia',
                'verbose_name_plural': 'Patologias o Enfermedades',
                'db_table': 'listado_general_patologico',
                'ordering': ['nombre_patologico'],
            },
        ),
    ]
